### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kfahn22**
I have been trying to change the auto encoder to color and can't figure out the right dimensions.

### CODE REVIEW

**Comment by meiamsome** [comment]
Hey there! Are you able to make this as a separate entry under the existing ones?

If you don't feel able to or are not sure how I can do it for you if you would like!

Thanks!

**Comment by kfahn22** [comment]
I guess I am not sure how to do it.  I tried submitting a pull request, did it come under your submission?

**Comment by meiamsome** [comment]
@kfahn22 Yep, no worries, I have merged your PR and fixed the issue. Thanks for your submission!

**Comment by kfahn22** [comment]
Thanks!

**Pull request merged**
